### ISSUE TITLE
uwsgi_curl strips leading slash

### ISSUE THREAD

**Issue by deric** [andreif/uwsgi-tools#1]
Is it possible to send request including leading `/`?

a request 

```
uwsgi_curl localhost:3000 /
```

is translated into:

```
GET  => generated 17 bytes in 0 msecs (HTTP/1.1 200) 
```

while standard `curl` would generate:

```
GET / => generated 17 bytes in 0 msecs (HTTP/1.1 200)
```

My backend is sensitive to leading slashes, and I'm unable to send request like `/health`

```
$ uwsgi_curl localhost:3000 /health
GET health => generated 81 bytes in 0 msecs (HTTP/1.1 404)
```

**Comment by andreif** [comment]
@deric Thanks! Fixed in https://pypi.python.org/pypi/uwsgi-tools/1.0.3

**Comment by deric** [comment]
Cool, thanks!
